"""add pinturas table

Revision ID: e5f75d534e84
Revises: a3f5c9b2d1e7
Create Date: 2026-04-30 20:17:55.064684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5f75d534e84'
down_revision: Union[str, Sequence[str], None] = 'a3f5c9b2d1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop FK constraint before dropping categorias table
    op.drop_constraint(op.f('pinturas_categoria_id_fkey'), 'pinturas', type_='foreignkey')
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_table('categorias')
    # Remove old pinturas columns
    op.drop_column('pinturas', 'descripcion')
    op.drop_column('pinturas', 'imagen_url')
    op.drop_column('pinturas', 'imagen_thumb')
    op.drop_column('pinturas', 'creado_en')
    op.drop_column('pinturas', 'titulo')
    op.drop_column('pinturas', 'destacada')
    op.drop_column('pinturas', 'actualizado_en')
    op.drop_column('pinturas', 'categoria_id')
    op.drop_column('pinturas', 'artista')
    op.drop_column('pinturas', 'activa')
    op.drop_column('pinturas', 'anio')
    op.drop_column('pinturas', 'orden')
    # Add new pinturas columns
    op.add_column('pinturas', sa.Column('autor', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('pinturas', sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('pinturas', sa.Column('año', sa.Integer(), nullable=True))
    op.add_column('pinturas', sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('pinturas', sa.Column('url_imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('pinturas', sa.Column('filename_original', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('pinturas', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_pinturas_autor'), 'pinturas', ['autor'], unique=False)
    op.create_index(op.f('ix_pinturas_categoria'), 'pinturas', ['categoria'], unique=False)
    op.create_unique_constraint(None, 'pinturas', ['filename_original'])
    # Remove server defaults after adding columns
    op.alter_column('pinturas', 'autor', server_default=None)
    op.alter_column('pinturas', 'nombre', server_default=None)
    op.alter_column('pinturas', 'categoria', server_default=None)
    op.alter_column('pinturas', 'url_imagen', server_default=None)
    op.alter_column('pinturas', 'filename_original', server_default=None)
    op.alter_column('pinturas', 'created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinturas', sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pinturas', sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pinturas', sa.Column('activa', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('pinturas', sa.Column('artista', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pinturas', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pinturas', sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('pinturas', sa.Column('destacada', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('pinturas', sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('pinturas', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('pinturas', sa.Column('imagen_thumb', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pinturas', sa.Column('imagen_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('pinturas', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('pinturas_categoria_id_fkey'), 'pinturas', 'categorias', ['categoria_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'pinturas', type_='unique')
    op.drop_index(op.f('ix_pinturas_categoria'), table_name='pinturas')
    op.drop_index(op.f('ix_pinturas_autor'), table_name='pinturas')
    op.drop_column('pinturas', 'created_at')
    op.drop_column('pinturas', 'filename_original')
    op.drop_column('pinturas', 'url_imagen')
    op.drop_column('pinturas', 'categoria')
    op.drop_column('pinturas', 'año')
    op.drop_column('pinturas', 'nombre')
    op.drop_column('pinturas', 'autor')
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categorias_pkey')),
    sa.UniqueConstraint('slug', name=op.f('categorias_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    # ### end Alembic commands ###
